version: "3"
services:
  back-end:
    build:
      context: ../back-end
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ../back-end:/usr/src/app
      - ../back-end/node_modules:/usr/src/app/node_modules
      - ../back-end/prisma:/usr/src/app/prisma 
